server:
  port: 18082
# 以下配置放入配置中心管理，读取配置中心的配置需要在启动类加注解 @RefreshScope
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # 注册中心地址
#    sentinel:
#      transport:
#        dashboard: localhost:8080 #sentinel地址
#        port: 8719 #交互端口
#  zipkin:
#    base-url: http://localhost:9411 #zipkin地址
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1 #采集率
#  datasource: # mysql数据源
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.157.132:3306/guli_sms
#    username: root
#    password: 123456
#  redis: #redis地址
#    host: 192.168.157.132
feign:
  sentinel:
    enabled: true # 开启feign的sentinel功能
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml #mp的映射文件地址
  type-aliases-package: com.atguigu.gmall.sms.entity #类型别名扫描包
  global-config:
    db-config:
      id-type: auto #id生成策略