server:
  port: 8888 # 端口号
# 以下配置放入配置中心管理，读取配置中心的配置需要在启动类加注解 @RefreshScope
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos注册中心地址
    gateway:
      routes: #路由
        - id: pms-route  # 商品管理路由
          uri: lb://pms-service
          predicates: # 断言匹配，下一行表示接受 /pms/ 下的所有请求
            - Path=/pms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**

