server:
  port: 18081 # 端口号
# 以下配置放入配置中心管理，读取配置中心的配置需要在启动类加注解 @RefreshScope
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # nacos注册中心地址
#    sentinel:
#      transport:
#        dashboard: localhost:8080 # sentinel地址
#        port: 8719 # 交互的端口号
#  zipkin:
#    base-url: http://localhost:9411 # zipkin地址
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1 # 采集率设置为1，全部采集
#  datasource: # mysql数据库的数据源
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.157.132:3306/guli_pms
#    username: root
#    password: 123456
#  redis: # redis的地址
#    host: 192.168.157.132
feign:
  sentinel:
    enabled: true # 开启feign的sentinel功能
mybatis-plus: # mp的映射文件地址
  mapper-locations: classpath:mapper/pms/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity # 类型别名扫描包
  global-config:
    db-config:
      id-type: auto # id自增策略
#logging:
#  level:
#    com.atguigu.gmall: debug
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  rabbitmq:
    host: 192.168.157.132
    virtual-host: /muran
    username: muran
    password: muran
    publisher-confirm-type: correlated
    publisher-returns: true

